coach_me/trainings/urls.py
from django.urls import path, include
from coach_me.trainings.views import TrainingCreateView, \
    TrainingDetailsView, TrainingUpdateView, TrainingDeleteView, TrainingListView

urlpatterns = (
    path('trainings/', TrainingListView.as_view(), name='trainings'),
    path('training/add/', TrainingCreateView.as_view(), name='add training'),

    path('training/<slug:slug>/', include([
        path('details/', TrainingDetailsView.as_view(), name='details training'),
        path('edit/', TrainingUpdateView.as_view(), name='edit training'),
        path('delete/', TrainingDeleteView.as_view(), name='delete training'),
    ])),

)

coach_me/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('coach_me.accounts.urls')),
    path('', include('coach_me.bookings.urls')),
    path('', include('coach_me.profiles.urls')),
    path('', include('coach_me.lectors.urls')),
    path('', include('coach_me.trainings.urls')),
]

handler500 = TemplateView.as_view(template_name='500.html')

coach_me/trainings/models.py
from django.db import models
from django.utils.text import slugify


class Training(models.Model):
    MAX_SERVICE_NAME_LENGTH = 50
    SLUG_MAX_LENGTH = 254

    service_name = models.CharField(
        max_length=MAX_SERVICE_NAME_LENGTH,
        default=None,
    )
    service_description = models.TextField(default="Add training description")
    service_image = models.URLField(default='https://freesvg.org/img/1380565395.png')

    slug = models.SlugField(
        max_length=SLUG_MAX_LENGTH,
        unique=True,
        blank=True)

    inserted_on = models.DateTimeField(auto_now_add=True)  # ,  auto_now=True for update
    updated_on = models.DateTimeField(auto_now=True)  # ,  auto_now=True for update

    def save(self, *args, **kwargs):
        if not self.slug:
            super().save(*args, **kwargs)
            self.slug = slugify(f"{self.pk}-{self.service_name}")
        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.service_name}'

coach_me/trainings/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, IsStaffdMixin
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic as views
from coach_me.profiles.models import BookingUserProfile
from coach_me.trainings.models import Training
from coach_me.bookings.mixins import DefineModelsMixin
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

UserModel = get_user_model()


class TrainingListView(views.ListView):
    # model = Training
    template_name = 'bookings/../../templates/trainings/trainings.html'
    paginate_by = 4
    queryset = Training.objects.all().order_by('-updated_on')

    # @method_decorator(cache_page(3600))  # Cache will expire in 1 hour (3600 seconds)
    # def dispatch(self, *args, **kwargs):
    #     return super().dispatch(*args, **kwargs)


class TrainingCreateView(IsStaffdMixin, views.CreateView):
    model = Training
    template_name = 'trainings/create-training.html'
    fields = '__all__'
    success_url = reverse_lazy('trainings')

    def form_valid(self, form):
        # Save the Lector instance and redirect to the success URL
        self.object = form.save()
        return redirect(self.get_success_url())


class TrainingDetailsView(views.DetailView):
    model = Training
    template_name = 'trainings/details-training.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        booking_user_profile = BookingUserProfile.objects.filter(pk=user.pk).get()

        available_lectors = DefineModelsMixin.get_lectors_by_training(self.object, list_csv=True)

        context['booking_user_profile'] = booking_user_profile
        context['user'] = user
        context['available_lectors'] = available_lectors

        return context


class TrainingUpdateView(IsStaffdMixin, views.UpdateView):
    model = Training
    template_name = 'trainings/edit-training.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('details training', kwargs={'slug': self.object.slug})


class TrainingDeleteView(IsStaffdMixin, views.DeleteView):
    model = Training
    template_name = 'trainings/delete-training.html'
    success_url = reverse_lazy('trainings')

    def get_form(self, form_class=None):
        form = super().get_form(form_class)
        for field_name in form.fields:
            # form.fields[field_name].widget.attrs['readonly'] = True
            form.fields[field_name].widget.attrs['disabled'] = True
        return form

templates/trainings/create-training.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main style="padding: 2%">
    <section class="text-center text-lg-start">
        <style>
            .cascading-right {
                margin-right: -50px;
            }

            @media (max-width: 992px) {
                .cascading-right {
                    margin-right: 0;
                }
            }
        </style>
        <!-- Jumbotron -->
        <div class="container py-4" style="
                {#display: flex;#}
                justify-content: center;
                align-items: center;
                height: 100vh;
                width: 100vh;">

            <div class="row g-0 align-items-center" style="padding-top: 5%">
                <div class="col-lg-6 mb-5 mb-lg-0">
                    <div class="card cascading-right" style="
            background: hsla(0, 0%, 100%, 0.55);
            backdrop-filter: blur(30px);
            ">
                        <div class="card-body p-5 shadow-5 text-center">
                            <form action="{% url 'add training' %}" method="post">
                                <input type="hidden" value="{{ next }}" name="next"/>
                                {% csrf_token %}
                                <h2 class="fw-bold mb-5">Add Training</h2>

                                <div class="form-outline mb-4" style="text-align: left;">
                                    {% include 'common/bs4_form.html' with form=form %}

                                </div>
                                <!-- Submit button -->
                                <button type="submit" class="btn btn-primary btn-block mb-4">Save</button>
                                <!-- Cancel button -->
                                <button type="button" class="btn btn-primary btn-block mb-4" id="cancelButton">Cancel</button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</main>
    <script>
        // Add event listener to the Cancel button
        document.getElementById('cancelButton').addEventListener('click', function () {
            // Navigate to the dashboard page when the Cancel button is clicked
            window.location.href = "{% url 'trainings' %}";
        });
    </script>
{% endblock %}

templates/trainings/delete-training.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main style="padding: 2%">
    <section class="text-center text-lg-start" id="delete">
        <div class="container">
            <p>
            <h1 style="
            color: crimson;
            display: inline-block;
                ">Are you sure you want to delete Training:</h1>
            <h1 style="
            color: #007bff;
            display: inline-block;"> &nbsp;{{ training.service_name }}</h1>
            <h1 style="
            color: crimson;
            display: inline-block;">?</h1>
            </p>
            <p>&nbsp;</p>
            <form class="delete-form" action="{% url 'delete training' slug=training.slug %}" method="post">
                {% csrf_token %}

                <div class="col-md-4">
                    <img src="{{ training.service_image }}" class="w-100 rounded-4 shadow-4"
                         alt="{{ training.service_name }} image"/>
                    <p></p>
                </div>
                <div class="col-md-4">
                    <p>{{ training.service_description }}</p>
                </div>
                <button class="btn btn-primary btn-block mb-4 btn btn-danger" type="submit">
                    Delete Training
                </button>
            </form>
        </div>
    </section>
</main>
{% endblock %}

templates/trainings/details-training.html
{% extends 'base.html' %}
{% load forms %}
{% load static %}
{% block content %}
    <main style="padding: 2%">
        <div class="container card" style="padding: 5%">
            <div class="row">
                <div class="col">
                    <div class="flex-container">
                        <div class="flex-container">
                            <input type="hidden" value="{{ next }}" name="next"/>
                            {% csrf_token %}
                            <div class="form-outline mb-4" style="text-align: left;">
                                {% if training.service_image is not None %}
                                    <div class="colM"
                                         style="text-align: left;
                             width: 90%;
                             height: 70%;">
                                        <img src="{{ training.service_image }}" class="w-100 rounded-4 shadow-4"
                                             alt="login screen"/>
                                        <p></p>
                                    </div>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="flex-container">
                        <div class="flex-container">
                            <input type="hidden" value="{{ next }}" name="next"/>
                            {% csrf_token %}
                            <div class="form-outline mb-4" style="text-align: left;">
                                <h2 class="fw-bold mb-5" style="text-align: center">
                                    {{ training.service_name }}
                                </h2>
                                <p><strong>Training info: </strong> {{ training.service_description }}</p>
                                <p><strong>Available lectors: </strong> {{ available_lectors }}</p>
                            </div>

                            {#                            <a href="{% url 'add booking' %}" class="btn btn-primary">#}
                            {#                                    Book this Training#}
                            {#                                </a>#}
                            {% if user.c_labels != 'COACHME_LECTOR' %}
                            <a href="{% url 'add booking' %}?training={{ object.slug }}" class="btn btn-primary">
                                Book this Training
                            </a>
                            {% endif %}
                            {% if user.is_staff %}
                                <!-- Delete Profile Button -->
                                <a href="{% url 'delete training' slug=object.slug %}" class="btn btn-danger">
                                    Delete
                                </a>
                                <!-- Edit Profile Button -->
                                <a href="{% url 'edit training' slug=object.slug %}" class="btn btn-primary">
                                    Edit
                                </a>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/trainings/edit-training.html
{% extends 'base.html' %}
{% load static %}
{% load forms %}

{% block content %}

    {#    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css">#}
    {#    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js"></script>#}
    <main style="padding: 2%">

        <section class="text-center text-lg-start">
            <style>
                .cascading-right {
                    margin-right: -50px;
                }

                @media (max-width: 992px) {
                    .cascading-right {
                        margin-right: 0;
                    }
                }
            </style>
            <!-- Jumbotron -->
            <div class="container py-4" style="
                    {#display: flex;#}
                    justify-content: center;
                    align-items: center;
                    height: 100vh;">

                <div class="row g-0 align-items-center" style="padding-top: 5%">
                    <div class="col-lg-6 mb-5 mb-lg-0">
                        <div class="card cascading-right" style="
            background: hsla(0, 0%, 100%, 0.55);
            backdrop-filter: blur(30px);
            ">
                            <div class="card-body p-5 shadow-5 text-center">

                                <h2 class="fw-bold mb-5">Edit Training</h2>
                                {#                            <link rel="stylesheet" href="{% static '/css/styles.css' %}"/>#}
                                <img class="rounded-image"
                                     src="{{ object.service_image }}"
                                     alt="Training Picture"
                                     style="
                                 width: 50%;
                                 height: 40%;
                                    ">

                                <form action="{% url 'edit training' object.slug %}" method="post">

                                    <input type="hidden" value="{{ next }}" name="next"/>

                                    {% csrf_token %}

                                    <div class="form-outline mb-4" style="text-align: left;">
                                        {% include 'common/bs4_form.html' with form=form %}

                                    </div>
                                    <!-- Submit button -->
                                    <button type="submit" class="btn btn-primary btn-block mb-4">
                                        Save
                                    </button>
                                    <!-- Cancel button -->
                                    <button type="button" class="btn btn-primary btn-block mb-4" id="cancelButton">
                                        Cancel
                                    </button>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    {#        <script>#}
    {#        // Add event listener to the Cancel button#}
    {#        document.getElementById('cancelButton').addEventListener('click', function () {#}
    {#            // Navigate to the dashboard page when the Cancel button is clicked#}
    {#            window.location.href = "{% url 'details training' slug=object.slug %}";#}
    {#        });#}
    {#    </script>#}

    <script>
        // Add event listener to the Cancel button
        document.getElementById('cancelButton').addEventListener('click', function () {
            // Navigate to the dashboard page when the Cancel button is clicked
            window.location.href = "{% url 'details training' object.slug %}";
        });

        // Add event listener to the form submission
        document.querySelector('form').addEventListener('submit', function (event) {
            event.preventDefault(); // Prevent the default form submission behavior

            // Submit the form using JavaScript
            this.submit();
        });
    </script>


{% endblock %}

templates/trainings/trainings.html
{% extends 'base.html' %}
{% load forms %}
{% load static %}
{% block content %}

    <main style="padding: 2%">
        <div class="container">
            <div id="intro" class="p-5 text-center bg-light">
                <h1 class="mb-3 h2">Streamline Your Corporate Training Bookings with Ease</h1>
                <p class="mb-3">Effortlessly schedule and manage soft skills training for your
                    employees with our
                    intuitive
                    booking system. Empower your workforce with valuable professional development
                    opportunities.</p>
                <p>&nbsp;<hr/></p>

                <p>&nbsp;</p>
                {% for training in training_list %}
                    <!-- Post -->
                    <div class="row" style="text-align: left;">
                        <div class="col-md-4 mb-4">
                            <div class="bg-image hover-overlay shadow-1-strong rounded ripple"
                                 data-mdb-ripple-color="light">
                                <img src="{{ training.service_image }}"
                                     class="img-fluid" alt="{{ training.service_name }}"/>
                                <a href="#!">
                                    {#                                            TODO hrfe above - needed or not #}
                                    <div class="mask"
                                         style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-8 mb-4">
                            <h5>{{ training.service_name }}</h5>
                            <p>
                                {{ training.service_description }}
                            </p>
                            {% if user.is_authenticated %}
{#                            <button type="button" >#}
                                <a href="{% url 'details training' slug=training.slug %}"
                                   style="text-decoration: white; color: deepskyblue;">
                                    Details
                                </a>
{#                            </button>#}
                            {% endif %}
                        </div>
                    </div>
                <p>&nbsp;<hr/>&nbsp;</p>
                {% endfor %}

            {% include 'core/pagination.html' %}

            </div>
        </div>
    </main>

{% endblock %}