coach_me/accounts/urls.py
from django.urls import path
from coach_me.accounts.views import RegisterUserView, LoginUserView, LogoutUserView

urlpatterns = (
    path('register/', RegisterUserView.as_view(), name='register_user'),
    path('login/', LoginUserView.as_view(), name='login_user'),
    path('logout/', LogoutUserView.as_view(), name='logout_user'),
)

coach_me/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('coach_me.accounts.urls')),
    path('', include('coach_me.bookings.urls')),
    path('', include('coach_me.profiles.urls')),
    path('', include('coach_me.lectors.urls')),
    path('', include('coach_me.trainings.urls')),
]

handler500 = TemplateView.as_view(template_name='500.html')

coach_me/accounts/models.py
from django.db import models
from django.contrib.auth import models as auth_models
from coach_me.accounts.managers import BookingUserManager
from django.contrib.auth.models import AbstractUser, Group


class BookingUser(auth_models.AbstractBaseUser, auth_models.PermissionsMixin):
    GROUP_CHOICES = (
        ('COACHME_STAFF', 'COACHME_STAFF'),
        ('COACHME_LECTOR', 'COACHME_LECTOR'),
        ('COACHME_USER', 'COACHME_USER'),
    )
    GROUPS_CHOICES_MAX_LEN = max(len(choice[1]) for choice in GROUP_CHOICES)
    email = models.EmailField(
        null=False,
        blank=False,
        unique=True,
        verbose_name="Corporate email",
    )

    date_joined = models.DateTimeField(
        auto_now_add=True,
    )

    is_staff = models.BooleanField(
        default=False,
    )
    #
    # groups = models.ManyToManyField(
    #     Group,
    #     blank=True,
    #     related_name='users',
    # )
    #
    c_labels = models.CharField(
        max_length=GROUPS_CHOICES_MAX_LEN,
        null=True,
        blank=True,
        default='COACHME_USER',
        choices=(
            GROUP_CHOICES
        ),
        verbose_name="COACHME Groups",
    )

    USERNAME_FIELD = 'email'
    objects = BookingUserManager()

    def __str__(self):
        return f'{self.email}'

    def __repr__(self):
        return f'ID {self.id}: {self.email}'

coach_me/accounts/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms, get_user_model
from django.utils.translation import gettext_lazy as _
from coach_me.profiles.models import BookingUserProfile


UserModel = get_user_model()


class LoginUserForm(auth_forms.AuthenticationForm):

    username = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                'style': 'border-color: blue;',
                'placeholder': 'Enter your email',
                'class': 'form-control',
            }
        )
    )

    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                'style': 'border-color: blue;',
                'placeholder': 'Enter your password',
                'content': '*',
                'autocomplete': 'off',
                'render_value': True,
                'class': 'form-control',
            }
        )
    )

    class Meta(auth_forms.UserCreationForm.Meta):
        model = UserModel
        fields = '__all__'
        widgets = {
            'username': forms.TextInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'username pls',
                }),
            'password': forms.PasswordInput(
                attrs={
                    'class': 'form-control',
                    'placeholder': 'pass pls',
                }),
        }


class RegisterUserForm(auth_forms.UserCreationForm):
    first_name = forms.CharField(
        label=_("First name"),
        widget=forms.TextInput(
            attrs={
                'style': 'border-color: blue;',
                'placeholder': 'First name',
                'title': 'First name',
                # 'label': 'First name',

            },
        )
    )

    last_name = forms.CharField(
        label=_("Last name"),
        widget=forms.TextInput(
            attrs={
                'style': 'border-color: blue;',
                'placeholder': 'Last name',
                # 'label': 'Last name',
            },
        )
    )

    email = forms.CharField(
        label=_("Corporate email"),
        widget=forms.EmailInput(
            attrs={
                'style': 'border-color: blue;',
                'placeholder': 'Enter your corporate email',
                # 'label': 'Corporate email',
            },
        )
    )

    password1 = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(
            attrs={
                'style': 'border-color: blue;',
                # 'placeholder': 'Password',
                # 'label': 'Password',
            },
        )
    )

    password2 = forms.CharField(
        label=_("Repeat Password"),
        widget=forms.PasswordInput(
            attrs={
                'style': 'border-color: blue;',
                'placeholder': 'Repeat password',
                "autocomplete": "new-password",
                # 'label': 'Repeat Password',
                # 'is_hidden': True,
                # "required": False,
            },
        )
    )

    consent_terms = forms.BooleanField(
        widget=forms.CheckboxInput,
        label=_("Agree to Terms and Conditions"),
    )
    newsletter_subscription = forms.BooleanField(
        widget=forms.CheckboxInput,
        label=_("Subscribe to our newsletter"),
        required=False,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].help_text = _('Please enter your password')
        self.fields['password2'].help_text = _('Please repeat your password')
        self.fields['email'].help_text = _('Use your company email address')

    def save(self, commit=True):
        user = super().save(commit)

        profile = BookingUserProfile(
            first_name=self.cleaned_data['first_name'],
            last_name=self.cleaned_data['last_name'],
            consent_terms=self.cleaned_data['consent_terms'],
            newsletter_subscription=self.cleaned_data['newsletter_subscription'],
            user=user,
        )
        if commit:
            profile.save()

        return user

    class Meta(auth_forms.UserCreationForm.Meta):
        model = UserModel
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password1': forms.PasswordInput(attrs={'class': 'form-control'}),
            'password2': forms.PasswordInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'consent_terms': forms.CheckboxInput(attrs={'class': 'form-check-input me-2'}),
            'newsletter_subscription': forms.CheckboxInput(attrs={'class': 'form-check-input me-2'}),
        }

coach_me/accounts/templatetags/forms.py
from django import template

register = template.Library()


@register.filter
def placeholder(form_field, text):
    form_field.field.widget.attrs['placeholder'] = text
    return form_field


@register.filter
def form_field_class(form_field, class_name):
    default_classname = form_field.field.widget.attrs.get('class', '')
    form_field.field.widget.attrs['class'] = default_classname + ' ' + class_name
    return form_field

coach_me/accounts/views.py
from django.contrib.auth import views as auth_views, login
from django.urls import reverse_lazy
from django.views import generic as views
from coach_me.accounts.forms import LoginUserForm, RegisterUserForm
from coach_me.profiles.models import Company
from coach_me.bookings.mixins import AnonymousRequiredMixin
import logging

logger = logging.getLogger(__name__)


class RegisterUserView(AnonymousRequiredMixin, views.CreateView):
    template_name = 'accounts/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        placeholders = {
            'first_name': 'First name',
            'last_name': 'Last name',
            'email': 'Enter your corporate email',
            'password1': 'Password',
            'password2': 'Repeat password',
        }
        context['placeholders'] = placeholders
        return context

    def form_valid(self, form):
        # Check if the employee corporate email has the correct domain name suffix
        existing_domains = Company.objects.filter(
            company_domain__iendswith=str(form.instance.email).split('@')[1]
        ).exists()

        if not existing_domains:
            error_message = """
                    We can't find your company domain in our database! 
                    Please contact our team for support or check if the corporate email address is correct!
                    """
            logger.warning(f"User registration error: {error_message}")
            form.add_error(None, error_message)
            return self.form_invalid(form)

        result = super().form_valid(form)
        login(self.request, self.object)
        logger.info(f"User registration: {object}")
        return result


class LoginUserView(auth_views.LoginView):
    template_name = 'accounts/login.html'
    form_class = LoginUserForm
    success_url = reverse_lazy('dashboard')

    def form_invalid(self, form):
        logger.warning("User login failed: Invalid credentials")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        placeholders = {
            'username': 'Enter your corporate email',
            'password': 'Password',
        }
        context['placeholders'] = placeholders
        return context


class LogoutUserView(auth_views.LogoutView):
    def logout(self, request):
        logger.info(f"User logged out: {request.user}")
        return super().logout(request)

templates/accounts/login.html
{#{% extends 'base.html' %}#}
{% load forms %}
{% load static %}

{% include 'common/../core/head.html' %}

<!-- Section: Design Block -->
<section class="text-center text-lg-start">
    <style>
        .cascading-right {
            margin-right: -50px;
        }

        @media (max-width: 992px) {
            .cascading-right {
                margin-right: 0;
            }
        }
    </style>

    <!-- Jumbotron -->
    <div class="container py-4" style="
            {#display: flex;#}
            text-align: center;
            justify-content: center;
            align-items: center;
            height: 100vh;
            width: 100vh;">
        <div class="row g-0 align-items-center" style="padding-top: 10%">
            <div class="col-lg-6 mb-5 mb-lg-0">
                <div class="card cascading-right" style="
                        background: hsla(0, 0%, 100%, 0.55);
                        backdrop-filter: blur(30px);
                        {#padding-top: 30%;#}
                        ">
                    <div class="card-body p-5 shadow-5 text-center">

                        <a class="navbar-brand" href="{% url 'index' %}">
                            <img id="logo-img" src="{% static '/images/logo.png' %}" alt="logo"/></a>
                        <h2 class="fw-bold mb-5">Login now</h2>
                        <form action="{% url 'login_user' %}" method="post">
                            <input type="hidden" value="{{ next }}" name="next"/>

                            {% csrf_token %}
                            <div class="form-outline mb-4" style="text-align: left;">
                                {% include 'common/bs4_form.html' with form=form placeholders=placeholders%}
                            </div>

                            <!-- Submit button -->
                            <button type="submit" class="btn btn-primary btn-block mb-4">
                                Login &nbsp
                            </button>
                            &nbsp or &nbsp
                            <a class="reg-link" href="{% url 'register_user' %}">
                                Register here</a>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 mb-5 mb-lg-0">
                <img src="{% static '/images/login.jpg' %}" class="w-100 rounded-4 shadow-4"
                     alt="login screen"/>
            </div>
        </div>
    </div>
</section>

templates/accounts/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/accounts/register.html
{#{% extends 'base.html' %}#}
{% load forms %}
{% load static %}
{#{% block content %}#}
{#{{ request.user }}#}

{% include 'common/../core/head.html' %}

<!-- Section: Design Block -->
<section class="text-center text-lg-start">
    <style>
        .cascading-right {
            margin-right: -50px;
        }

        @media (max-width: 992px) {
            .cascading-right {
                margin-right: 0;
            }
        }
    </style>

    <!-- Jumbotron -->
    <div class="container py-4">
        <div class="row g-0 align-items-center" style="padding-top: 5%">
            <div class="col-lg-6 mb-5 mb-lg-0">
                <div class="card cascading-right" style="
            background: hsla(0, 0%, 100%, 0.55);
            backdrop-filter: blur(30px);
            ">
                    <div class="card-body p-5 shadow-5 text-center">
                        <a class="navbar-brand" href="{% url 'index' %}">
                            <img id="logo-img" src="{% static '/images/logo.png' %}" alt="logo"/></a>

                        <h2 class="fw-bold mb-5">Sign up now</h2>

                        <form action="{% url 'register_user' %}" method="post">

                            <input type="hidden" value="{{ next }}" name="next"/>

                            <!-- 2 column grid layout with text inputs for the first and last names -->

                            <!-- Email input -->
                            <div class="form-outline mb-4" style="text-align: left;">
                                {% include 'common/bs4_form_only_placeholders.html' with form=form placeholders=placeholders %}
                            </div>
                            {##}
                            {#                            <!-- Password input -->#}
                            {#                            <div class="form-outline mb-4">#}
                            {#                                <label for="password1"></label><input type="password" name="password1"#}
                            {#                                                                      autocomplete="new-password" required=""#}
                            {#                                                                      id="password1" class="form-control"#}
                            {#                                                                      placeholder="Password"/>#}
                            {#                                <label class="form-label" for="password"></label>#}
                            {#                            </div>#}
                            {##}
                            {#                            <!-- Repeat Password input -->#}
                            {#                            <div class="form-outline mb-4">#}
                            {#                                <input type="password" name="password2" autocomplete="new-password" required=""#}
                            {#                                       id="id_password2" class="form-control" placeholder="Repeat password"/>#}
                            {#                                <label class="form-label" for="id_password2"></label>#}
                            {#                            </div>#}
                            {##}
                            <!-- Checkbox -->
{#                            <div class="form-check d-flex justify-content-center mb-4">#}
{#                                <input class="form-check-input me-2" type="checkbox" name="newsletter_subscription"#}
{#                                       required="" id="id_newsletter_subscription" checked/>#}
{#                                <label class="form-check-label" for="id_newsletter_subscription">#}
{#                                    Subscribe to our newsletter#}
{#                                </label>#}
{#                            </div>#}
{##}
{#                            <!-- Checkbox -->#}
{#                            <div class="form-check d-flex justify-content-center mb-4">#}
{#                                <input class="form-check-input me-2" type="checkbox" name="consent_terms" required=""#}
{#                                       id="id_consent_terms" checked/>#}
{#                                <label class="form-check-label" for="id_consent_terms">#}
{#                                    Agree to Terms and Conditions#}
{#                                </label>#}
{#                            </div>#}

                            {% csrf_token %}

                            <!-- Submit button -->
                            <button type="submit" class="btn btn-primary btn-block mb-4">
                                Sign up
                            </button>
                            or
                            <a class="reg-link" href="{% url 'login_user' %}?next={{ next }}">
                                Login here</a>

                            <!-- Register buttons -->
                            <div class="text-center">

                            </div>
                        </form>
                    </div>
                </div>
            </div>

            <div class="col-lg-6 mb-5 mb-lg-0">
                <img src="{% static '/images/signup.jpg' %}" class="w-100 rounded-4 shadow-4"
                     alt=""/>
            </div>
        </div>
    </div>

</section>