coach_me/lectors/urls.py
from django.urls import path, include
from coach_me.lectors.views import LectorListView, LectorDetailsView, LectorUpdateView, LectorDeleteView, \
    LectorCreateView

urlpatterns = (
    path('lectors/', LectorListView.as_view(), name='lectors'),
    path('lectors/add/', LectorCreateView.as_view(), name='add lector'),

    path('lector/<slug:slug>/', include([
        path('details/', LectorDetailsView.as_view(), name='details lector'),
        path('edit/', LectorUpdateView.as_view(), name='edit lector'),
        path('delete/', LectorDeleteView.as_view(), name='delete lector'),
    ])),

)

coach_me/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('coach_me.accounts.urls')),
    path('', include('coach_me.bookings.urls')),
    path('', include('coach_me.profiles.urls')),
    path('', include('coach_me.lectors.urls')),
    path('', include('coach_me.trainings.urls')),
]

handler500 = TemplateView.as_view(template_name='500.html')

coach_me/lectors/models.py
from django.core import validators
from django.db import models
from django.utils.text import slugify
from coach_me.accounts.models import BookingUser
from coach_me.trainings.models import Training
from coach_me.bookings.validators import validate_string_is_letters_only, \
    validate_string_is_letters_and_hyphens_only, \
    validate_phone_numbers_formatting


class Lector(models.Model):
    FIRST_NAME_MAX_LENGTH = 30
    FIRST_NAME_MIN_LENGTH = 2
    LAST_NAME_MAX_LENGTH = 30
    LAST_NAME_MIN_LENGTH = 2
    PHONE_MAX_LENGTH = 10
    SLUG_MAX_LENGTH = 254

    user = models.ForeignKey(
        BookingUser,
        on_delete=models.DO_NOTHING,
        # related_name='rel_bookings', #instead of employee_set
    )

    first_name = models.CharField(
        max_length=FIRST_NAME_MAX_LENGTH,
        null=False,
        blank=False,
        default=None,
        validators=(
            validators.MinLengthValidator(FIRST_NAME_MIN_LENGTH),
            validate_string_is_letters_only,
        ),
    )
    last_name = models.CharField(
        max_length=LAST_NAME_MAX_LENGTH,
        null=False,
        blank=False,
        default=None,
        validators=(
            validators.MinLengthValidator(LAST_NAME_MIN_LENGTH),
            validate_string_is_letters_and_hyphens_only,
        ),
    )
    phone = models.CharField(
        max_length=PHONE_MAX_LENGTH,
        null=False,
        blank=False,
        default=None,
        validators=(
            validate_phone_numbers_formatting,
        )
    )

    email = models.EmailField(
        null=False,
        blank=False,
        default=None,
    )
    lector_image = models.URLField(default='https://img.freepik.com/free-icon/user_318-159711.jpg')
    service_integrity = models.ManyToManyField(Training)

    biography = models.TextField()

    slug = models.SlugField(
        max_length=SLUG_MAX_LENGTH,
        unique=True,
        blank=True,
        null=True,
    )

    inserted_on = models.DateTimeField(auto_now_add=True)  # ,  auto_now=True for update
    updated_on = models.DateTimeField(auto_now=True)  # ,  auto_now=True for update

    @property
    def full_name(self):
        if self.first_name or self.last_name:
            return f"{self.first_name} {self.last_name}"

    def save(self, *args, **kwargs):
        # Generate the slug before saving the instance
        if not self.slug:
            full_name = f"{self.first_name} {self.last_name}"
            # self.slug = slugify(f"{self.pk}-{full_name}")
            self.slug = slugify(f"{full_name}")

        super().save(*args, **kwargs)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def __repr__(self):
        return f'{self.id}: {self.first_name} {self.last_name}'

coach_me/lectors/forms.py
from django import forms
from django.contrib.auth import forms as auth_forms, get_user_model
from django.utils.translation import gettext_lazy as _
from coach_me.accounts.models import BookingUser
from coach_me.lectors.models import Lector
from coach_me.profiles.models import BookingUserProfile

UserModel = get_user_model()


class LectorDashboardForm(forms.ModelForm):
    pass


class LectorList(forms.ModelForm):
    class Meta:
        model = Lector
        fields = '__all__'


class LectorUpdateForm(forms.ModelForm):
    class Meta:
        model = BookingUserProfile
        # fields = '__all__'
        exclude = ['consent_terms', 'newsletter_subscription', 'is_lector']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Hide the 'user' field
        self.fields['user'].widget = forms.HiddenInput()
        self.fields['date_of_birth'].help_text = _('in "YYYY-MM-DD" format')
        self.fields['phone'].help_text = _('starting with +359  (e.g "+35912345678")')
        # self.fields['email'].help_text = _('Use your company email address')


class LectorDeleteForm(forms.ModelForm):
    class Meta:
        model = Lector
        fields = '__all__'


class LectorDetailsForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Hide the 'user' field
        self.fields['is_lector'].widget = forms.HiddenInput()

    class Meta:
        model = Lector
        # fields = '__all__'
        exclude = ['user', 'consent_terms', 'newsletter_subscription', 'is_lector', ]

coach_me/lectors/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, IsStaffdMixin
from django.forms import modelform_factory
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views import generic as views

from coach_me.lectors.forms import LectorList
from coach_me.lectors.models import Lector
from coach_me.bookings.mixins import DefineModelsMixin
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page

from coach_me.profiles.models import BookingUserProfile

UserModel = get_user_model()


class LectorListView(views.ListView):
    model = Lector
    template_name = 'lectors/lectors.html'
    form_class = LectorList
    paginate_by = 2

    # @method_decorator(cache_page(1))  # Cache will expire in 1 hour (3600 seconds)
    # def dispatch(self, *args, **kwargs):
    #     return super().dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        # booking_user_profile = BookingUserProfile.objects.filter(pk=user.pk).get()
        # available_trainings = DefineModelsMixin.get_trainings_by_lector(self.object, True)
        #
        # context['available_lectors'] = available_trainings
        try:
            profile = BookingUserProfile.objects.get(pk=user.pk)
        except BookingUserProfile.DoesNotExist:
            profile = None

            context['booking_user_profile'] = profile
        context['user'] = user

        return context


class LectorCreateView(LoginRequiredMixin, IsStaffdMixin, views.CreateView):
    model = Lector
    template_name = 'lectors/create-lector.html'
    fields = '__all__'
    success_url = reverse_lazy('lectors')

    def form_valid(self, form):
        # Check if the BookingUser is already linked to another Lector

        lector_bookinguser_duplicate = Lector.objects.filter(
            user_id=form.instance.user_id,
        ).exists()

        if lector_bookinguser_duplicate:
            form.add_error(None, "This user was already linked to another Lector.")
            return self.form_invalid(form)

        return super().form_valid(form)


class LectorDetailsView(views.DetailView):
    model = Lector
    template_name = 'lectors/details-lector.html'

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super().get_context_data(**kwargs)
        booking_user_profile = BookingUserProfile.objects.filter(pk=user.pk).get()
        available_trainings = DefineModelsMixin.get_trainings_by_lector(self.object, False)

        context['booking_user_profile'] = booking_user_profile
        context['user'] = user
        context['available_trainings'] = available_trainings

        return context


class LectorUpdateView(LoginRequiredMixin, IsStaffdMixin, views.UpdateView):
    model = Lector
    template_name = 'lectors/edit-lector.html'
    fields = '__all__'

    def get_success_url(self):
        return reverse_lazy('details lector', kwargs={'slug': self.object.slug})


class LectorDeleteView(LoginRequiredMixin, IsStaffdMixin, views.DeleteView):
    model = Lector
    template_name = 'lectors/delete-lector.html'
    success_url = reverse_lazy('lectors')
    #
    #
    # def get_form(self, form_class=None):
    #     form = super().get_form(form_class)
    #     for field_name in form.fields:
    #         form.fields[field_name].widget.attrs['disabled'] = True
    #         # form.fields[field_name].widget.attrs['readonly'] = True
    #     return form

templates/lectors/create-lector.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main style="padding: 2%">
        <section class="text-center text-lg-start">
            <style>
                .cascading-right {
                    margin-right: -50px;
                }

                @media (max-width: 992px) {
                    .cascading-right {
                        margin-right: 0;
                    }
                }
            </style>
            <!-- Jumbotron -->
            <div class="container py-4" style="
                    {#display: flex;#}
                    justify-content: center;
                    align-items: center;
                    height: 100vh;
                    width: 100vh;">

                <div class="row g-0 align-items-center" style="padding-top: 5%">
                    <div class="col-lg-6 mb-5 mb-lg-0">
                        <div class="card cascading-right" style="
            background: hsla(0, 0%, 100%, 0.55);
            backdrop-filter: blur(30px);
            ">
                            <div class="card-body p-5 shadow-5 text-center">
                                <form action="{% url 'add lector' %}" method="post">
                                    <input type="hidden" value="{{ next }}" name="next"/>
                                    {% csrf_token %}
                                    <h2 class="fw-bold mb-5">Add Lector</h2>

                                    <div class="form-outline mb-4" style="text-align: left;">
                                        {% include 'common/bs4_form.html' with form=form %}

                                    </div>
                                    <!-- Submit button -->
                                    <button type="submit" class="btn btn-primary btn-block mb-4">
                                        Save
                                    </button>
                                    <!-- Cancel button -->
                                    <button type="button" class="btn btn-primary btn-block mb-4" id="cancelButton">
                                        Cancel
                                    </button>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <script>
        // Add event listener to the Cancel button
        document.getElementById('cancelButton').addEventListener('click', function () {
            // Navigate to the dashboard page when the Cancel button is clicked
            window.location.href = "{% url 'lectors' %}";
        });
    </script>
{% endblock %}

templates/lectors/delete-lector.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <main style="padding: 2%">
        <section class="text-center text-lg-start" id="delete">
            <div class="container">
                <p>
                <h1 style="
            color: crimson;
            display: inline-block;
                ">Are you sure you want to delete </h1>
                <h1 style="
            color: #007bff;
            display: inline-block;"> &nbsp;{{ object.full_name }}</h1>
                <h1 style="
            color: crimson;
            display: inline-block;">?</h1>
                </p>
                <p>&nbsp;</p>
                <!-- Delete Profile Form -->
                <form class="delete-form" action="{% url 'delete lector' lector.slug %}" method="post">
                    <!-- Confirm Button -->
                    {% csrf_token %}
                    <div class="col-md-4">
                        <img src="{{ object.lector_image }}" class="w-100 rounded-4 shadow-4"
                             alt="{{ lector.full_name }} image"/>
                        <p></p>
                    </div>
                    <button class="btn btn-primary btn-block mb-4 btn btn-danger" type="submit">
                        Delete Lector
                    </button>
                </form>
                <!-- End Delete Profile Form -->
            </div>
        </section>
    </main>
{% endblock %}

templates/lectors/details-lector.html
{% extends 'base.html' %}
{% load forms %}
{% load static %}
{% block content %}

    <main class="my-5">
        <div class="container">
            <main class="my-5">
                <div class="container">
                    <!--Section: Content-->
                    <section class="text-center">
                        <div class="row">
                            <!-- First Column - Display elements at even indexes -->
                            <div class="col-3 p-3 mb-2" style="padding: 5%">
                                <div class="card">
                                    <div class="bg-image hover-overlay ripple"
                                         data-mdb-ripple-color="light">
                                        <img src="{{ lector.lector_image }}" class="img-fluid"/>
                                        <a href="#!">
                                            <div class="mask"
                                                 style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                        </a>
                                    </div>
                                    <div class="card-body">
                                        <h5 class="card-title">{{ lector.full_name }}</h5>
                                        <p class="card-text"></p>
                                    </div>
                                </div>
                                <p></p>

                            </div>

                            <!-- Second Column - Display elements at odd indexes -->
                            <div class="col-sm-9 p-3"
                                 style="padding: 5%"
                            >
                                <div class="card">
                                    <div class="bg-image hover-overlay ripple"
                                         data-mdb-ripple-color="light">
                                        <img src="{{ training.service_image }}" class="img-fluid"/>
                                        <a href="#!">
                                            <div class="mask"
                                                 style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                        </a>
                                    </div>
                                    <div class="card-body" style="text-align: left">
                                        <h5 class="card-title">Bio: </h5>
                                        <p class="card-text">{{ lector.biography }}
                                        <p>
                                            <strong>Available trainings: </strong>
                                            {% for training in available_trainings %}
                                                <ul>
                                                    <li>
                                                        {{ training }}
                                                    </li>
                                                </ul>
                                            {% endfor %}

                                    </div>
                                </div>
                                <p></p>
                                {% if user.is_staff %}
                                    <!-- Delete Profile Button -->
                                    <a href="{% url 'delete lector' slug=object.slug %}"
                                       class="btn btn-danger">Delete</a>

                                    <!-- Edit Profile Button -->
                                    <a href="{% url 'edit lector' slug=object.slug %}"
                                       class="btn btn-primary">Edit</a>
                                {% endif %}
                            </div>
                        </div>
                    </section>
                </div>
            </main>
        </div>
    </main>

{% endblock %}

templates/lectors/edit-lector.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/pikaday/css/pikaday.css">
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/pikaday/pikaday.js"></script>
    <main style="padding: 2%">
        <section class="text-center text-lg-start">
            <style>
                .cascading-right {
                    margin-right: -50px;
                }

                @media (max-width: 992px) {
                    .cascading-right {
                        margin-right: 0;
                    }
                }
            </style>
            <!-- Jumbotron -->
            <div class="container py-4" style="
                    {#display: flex;#}
                    justify-content: center;
                    align-items: center;
                    height: 100vh;">
                <div class="row g-0 align-items-center" style="padding-top: 5%">
                    <div class="col-lg-6 mb-5 mb-lg-0">
                        <div class="card cascading-right" style="
            background: hsla(0, 0%, 100%, 0.55);
            backdrop-filter: blur(30px);
            ">
                            <div class="card-body p-5 shadow-5 text-center">
                                <h2 class="fw-bold mb-5">Edit Lector</h2>
                                <link rel="stylesheet" href="{% static '/css/styles.css' %}"/>
                                <img class="rounded-image"
                                     src="{{ object.lector_image }}"
                                     alt="Profile Picture"
                                     style="
                                 width: 50%;
                                 height: 40%;
                                    ">
                                <form action="{% url 'edit lector' slug=object.slug %}" method="post">

                                    <input type="hidden" value="{{ next }}" name="next"/>

                                    {% csrf_token %}

                                    <div class="form-outline mb-4" style="text-align: left;">
                                        {% include 'common/bs4_form.html' with form=form %}

                                    </div>
                                    <!-- Submit button -->
                                    <button type="submit" class="btn btn-primary btn-block mb-4">Save</button>
                                    <!-- Cancel button -->
                                    <button type="button" class="btn btn-primary btn-block mb-4" id="cancelButton">
                                        Cancel
                                    </button>

                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </main>
    <script>
        // Add event listener to the Cancel button
        document.getElementById('cancelButton').addEventListener('click', function () {
            // Navigate to the dashboard page when the Cancel button is clicked
            {#window.location.href = "{% url 'details lector' pk=object.pk %}";#}
            window.location.href = "{% url 'details lector' slug=object.slug %}";
        });
    </script>

{% endblock %}

templates/lectors/lectors.html
{% extends 'base.html' %}
{% load forms %}
{% load static %}
{% block content %}

    <main class="my-5">
        <div class="container">
            <div id="intro" class="p-5 text-center bg-light">
                <h1 class="mb-3 h2">Streamline Your Corporate Training Bookings with Ease</h1>
                <p class="mb-3">Effortlessly schedule and manage soft skills training for your
                    employees with our
                    intuitive
                    booking system. Empower your workforce with valuable professional development
                    opportunities.</p>
                <p>&nbsp;
                <hr/>
                </p>

                <p>&nbsp;</p>
                {% for lector in lector_list %}
                    <!-- Post -->
                    <div class="row" style="text-align: left;">
                        <div class="col-md-4 mb-4">
                            <div class="bg-image hover-overlay shadow-1-strong rounded ripple"
                                 data-mdb-ripple-color="light">
                                <img src="{{ lector.lector_image }}"
                                     class="img-fluid" alt="{{ lector.full_name }}"/>
                                <a href="#!">
                                    {#                                            TODO hrfe above - needed or not #}
                                    <div class="mask"
                                         style="background-color: rgba(251, 251, 251, 0.15);"></div>
                                </a>
                            </div>
                        </div>
                        <div class="col-md-8 mb-4">
                            <h5>{{ lector.full_name }}</h5>
                            <p>
                                {{ lector.biography }}
                            </p>
                            {% if user.is_authenticated %}
                                <a href="{% url 'details lector' slug=lector.slug %}"
                                   style="text-decoration: white; color: deepskyblue;">
                                    Details
                                </a>
                            {% endif %}
                        </div>
                    </div>
                    <p>&nbsp;
                    <hr/>&nbsp;</p>
                {% endfor %}

                <!-- Pagination -->
                {% include 'core/pagination.html' %}
            </div>
        </div>
    </main>

{% endblock %}